//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 13/05/2013 18:21:28
namespace HERBProject.DB.Infrastructure.Repositories.CustomBoundedRepository
{

    /// <summary>
    /// There are no comments for CustomBoundedDbEntities in the schema.
    /// </summary>
    public partial class CustomBoundedDbEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new CustomBoundedDbEntities object using the connection string found in the 'CustomBoundedDbEntities' section of the application configuration file.
        /// </summary>
        public CustomBoundedDbEntities() :
            base("name=CustomBoundedDbEntities", "CustomBoundedDbEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new CustomBoundedDbEntities object.
        /// </summary>
        public CustomBoundedDbEntities(string connectionString) :
            base(connectionString, "CustomBoundedDbEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new CustomBoundedDbEntities object.
        /// </summary>
        public CustomBoundedDbEntities(global::System.Data.EntityClient.EntityConnection connection) :
            base(connection, "CustomBoundedDbEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Input in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Input> Input
        {
            get
            {
                if ((this._Input == null))
                {
                    this._Input = base.CreateQuery<Input>("[Input]");
                }
                return this._Input;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Input> _Input;
        /// <summary>
        /// There are no comments for Input in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToInput(Input input)
        {
            base.AddObject("Input", input);
        }
    }
    /// <summary>
    /// There are no comments for CustomBoundedDataModel.Input in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName = "CustomBoundedDataModel", Name = "Input")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference = true)]
    [global::System.Serializable()]
    public partial class Input : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Input object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Input CreateInput(int id)
        {
            Input input = new Input();
            input.Id = id;
            return input;
        }
        /// <summary>
        /// There are no comments for property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty = true, IsNullable = false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _Id;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for property Property in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Property
        {
            get
            {
                return this._Property;
            }
            set
            {
                this.OnPropertyChanging(value);
                this.ReportPropertyChanging("Property");
                this._Property = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Property");
                this.OnPropertyChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Property;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnPropertyChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnPropertyChanged();
        /// <summary>
        /// There are no comments for property LastUpdate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<global::System.DateTime> LastUpdate
        {
            get
            {
                return this._LastUpdate;
            }
            set
            {
                this.OnLastUpdateChanging(value);
                this.ReportPropertyChanging("LastUpdate");
                this._LastUpdate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("LastUpdate");
                this.OnLastUpdateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<global::System.DateTime> _LastUpdate;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnLastUpdateChanging(global::System.Nullable<global::System.DateTime> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnLastUpdateChanged();
    }
}
