//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("HERBProject_DataBaseModel", "UsersProjects", "Project", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(HERBProject.DB.Infrastructure.Repositories.CustomBoundedRepository.Project), "User", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(HERBProject.DB.Infrastructure.Repositories.CustomBoundedRepository.User))]

// Original file name:
// Generation date: 16/10/2013 03:57:51 p.m.
namespace HERBProject.DB.Infrastructure.Repositories.CustomBoundedRepository
{
    
    /// <summary>
    /// There are no comments for HERBProject_DataBaseEntities in the schema.
    /// </summary>
    public partial class HERBProject_DataBaseEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new HERBProject_DataBaseEntities object using the connection string found in the 'HERBProject_DataBaseEntities' section of the application configuration file.
        /// </summary>
        public HERBProject_DataBaseEntities() : 
                base("name=HERBProject_DataBaseEntities", "HERBProject_DataBaseEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new HERBProject_DataBaseEntities object.
        /// </summary>
        public HERBProject_DataBaseEntities(string connectionString) : 
                base(connectionString, "HERBProject_DataBaseEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new HERBProject_DataBaseEntities object.
        /// </summary>
        public HERBProject_DataBaseEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "HERBProject_DataBaseEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Activity in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Activity> Activity
        {
            get
            {
                if ((this._Activity == null))
                {
                    this._Activity = base.CreateQuery<Activity>("[Activity]");
                }
                return this._Activity;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Activity> _Activity;
        /// <summary>
        /// There are no comments for Column in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Column> Column
        {
            get
            {
                if ((this._Column == null))
                {
                    this._Column = base.CreateQuery<Column>("[Column]");
                }
                return this._Column;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Column> _Column;
        /// <summary>
        /// There are no comments for Project in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Project> Project
        {
            get
            {
                if ((this._Project == null))
                {
                    this._Project = base.CreateQuery<Project>("[Project]");
                }
                return this._Project;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Project> _Project;
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<User> User
        {
            get
            {
                if ((this._User == null))
                {
                    this._User = base.CreateQuery<User>("[User]");
                }
                return this._User;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<User> _User;
        /// <summary>
        /// There are no comments for Activity in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToActivity(Activity activity)
        {
            base.AddObject("Activity", activity);
        }
        /// <summary>
        /// There are no comments for Column in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToColumn(Column column)
        {
            base.AddObject("Column", column);
        }
        /// <summary>
        /// There are no comments for Project in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToProject(Project project)
        {
            base.AddObject("Project", project);
        }
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToUser(User user)
        {
            base.AddObject("User", user);
        }
    }
    /// <summary>
    /// There are no comments for HERBProject_DataBaseModel.Activity in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id_activity
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="HERBProject_DataBaseModel", Name="Activity")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Activity : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Activity object.
        /// </summary>
        /// <param name="id_activity">Initial value of id_activity.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Activity CreateActivity(global::System.Guid id_activity)
        {
            Activity activity = new Activity();
            activity.id_activity = id_activity;
            return activity;
        }
        /// <summary>
        /// There are no comments for property id_activity in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Guid id_activity
        {
            get
            {
                return this._id_activity;
            }
            set
            {
                this.Onid_activityChanging(value);
                this.ReportPropertyChanging("id_activity");
                this._id_activity = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("id_activity");
                this.Onid_activityChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Guid _id_activity;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onid_activityChanging(global::System.Guid value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onid_activityChanged();
        /// <summary>
        /// There are no comments for property name_activity in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string name_activity
        {
            get
            {
                return this._name_activity;
            }
            set
            {
                this.Onname_activityChanging(value);
                this.ReportPropertyChanging("name_activity");
                this._name_activity = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("name_activity");
                this.Onname_activityChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _name_activity;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onname_activityChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onname_activityChanged();
        /// <summary>
        /// There are no comments for property hours_activity in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string hours_activity
        {
            get
            {
                return this._hours_activity;
            }
            set
            {
                this.Onhours_activityChanging(value);
                this.ReportPropertyChanging("hours_activity");
                this._hours_activity = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("hours_activity");
                this.Onhours_activityChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _hours_activity;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onhours_activityChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onhours_activityChanged();
        /// <summary>
        /// There are no comments for property docReque_activitiy in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string docReque_activitiy
        {
            get
            {
                return this._docReque_activitiy;
            }
            set
            {
                this.OndocReque_activitiyChanging(value);
                this.ReportPropertyChanging("docReque_activitiy");
                this._docReque_activitiy = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("docReque_activitiy");
                this.OndocReque_activitiyChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _docReque_activitiy;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OndocReque_activitiyChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OndocReque_activitiyChanged();
        /// <summary>
        /// There are no comments for property owner_activity in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string owner_activity
        {
            get
            {
                return this._owner_activity;
            }
            set
            {
                this.Onowner_activityChanging(value);
                this.ReportPropertyChanging("owner_activity");
                this._owner_activity = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("owner_activity");
                this.Onowner_activityChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _owner_activity;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onowner_activityChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onowner_activityChanged();
        /// <summary>
        /// There are no comments for property progress_activity in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string progress_activity
        {
            get
            {
                return this._progress_activity;
            }
            set
            {
                this.Onprogress_activityChanging(value);
                this.ReportPropertyChanging("progress_activity");
                this._progress_activity = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("progress_activity");
                this.Onprogress_activityChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _progress_activity;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onprogress_activityChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onprogress_activityChanged();
        /// <summary>
        /// There are no comments for property follow_activity in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<bool> follow_activity
        {
            get
            {
                return this._follow_activity;
            }
            set
            {
                this.Onfollow_activityChanging(value);
                this.ReportPropertyChanging("follow_activity");
                this._follow_activity = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("follow_activity");
                this.Onfollow_activityChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<bool> _follow_activity;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onfollow_activityChanging(global::System.Nullable<bool> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onfollow_activityChanged();
        /// <summary>
        /// There are no comments for property assigned_activity in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string assigned_activity
        {
            get
            {
                return this._assigned_activity;
            }
            set
            {
                this.Onassigned_activityChanging(value);
                this.ReportPropertyChanging("assigned_activity");
                this._assigned_activity = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("assigned_activity");
                this.Onassigned_activityChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _assigned_activity;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onassigned_activityChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onassigned_activityChanged();
        /// <summary>
        /// There are no comments for property description_activity in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string description_activity
        {
            get
            {
                return this._description_activity;
            }
            set
            {
                this.Ondescription_activityChanging(value);
                this.ReportPropertyChanging("description_activity");
                this._description_activity = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("description_activity");
                this.Ondescription_activityChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _description_activity;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Ondescription_activityChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Ondescription_activityChanged();
        /// <summary>
        /// There are no comments for property comments_activity in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string comments_activity
        {
            get
            {
                return this._comments_activity;
            }
            set
            {
                this.Oncomments_activityChanging(value);
                this.ReportPropertyChanging("comments_activity");
                this._comments_activity = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("comments_activity");
                this.Oncomments_activityChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _comments_activity;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Oncomments_activityChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Oncomments_activityChanged();
    }
    /// <summary>
    /// There are no comments for HERBProject_DataBaseModel.Column in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id_Column
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="HERBProject_DataBaseModel", Name="Column")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Column : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Column object.
        /// </summary>
        /// <param name="id_Column">Initial value of id_Column.</param>
        /// <param name="name_Column">Initial value of name_Column.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Column CreateColumn(global::System.Guid id_Column, string name_Column)
        {
            Column column = new Column();
            column.id_Column = id_Column;
            column.name_Column = name_Column;
            return column;
        }
        /// <summary>
        /// There are no comments for property id_Column in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Guid id_Column
        {
            get
            {
                return this._id_Column;
            }
            set
            {
                this.Onid_ColumnChanging(value);
                this.ReportPropertyChanging("id_Column");
                this._id_Column = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("id_Column");
                this.Onid_ColumnChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Guid _id_Column;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onid_ColumnChanging(global::System.Guid value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onid_ColumnChanged();
        /// <summary>
        /// There are no comments for property name_Column in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string name_Column
        {
            get
            {
                return this._name_Column;
            }
            set
            {
                this.Onname_ColumnChanging(value);
                this.ReportPropertyChanging("name_Column");
                this._name_Column = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("name_Column");
                this.Onname_ColumnChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _name_Column;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onname_ColumnChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onname_ColumnChanged();
        /// <summary>
        /// There are no comments for property position_Column in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<int> position_Column
        {
            get
            {
                return this._position_Column;
            }
            set
            {
                this.Onposition_ColumnChanging(value);
                this.ReportPropertyChanging("position_Column");
                this._position_Column = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("position_Column");
                this.Onposition_ColumnChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<int> _position_Column;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onposition_ColumnChanging(global::System.Nullable<int> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onposition_ColumnChanged();
    }
    /// <summary>
    /// There are no comments for HERBProject_DataBaseModel.Project in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id_Project
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="HERBProject_DataBaseModel", Name="Project")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Project : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Project object.
        /// </summary>
        /// <param name="id_Project">Initial value of id_Project.</param>
        /// <param name="name_Project">Initial value of name_Project.</param>
        /// <param name="description_Project">Initial value of description_Project.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Project CreateProject(global::System.Guid id_Project, string name_Project, string description_Project)
        {
            Project project = new Project();
            project.id_Project = id_Project;
            project.name_Project = name_Project;
            project.description_Project = description_Project;
            return project;
        }
        /// <summary>
        /// There are no comments for property id_Project in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Guid id_Project
        {
            get
            {
                return this._id_Project;
            }
            set
            {
                this.Onid_ProjectChanging(value);
                this.ReportPropertyChanging("id_Project");
                this._id_Project = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("id_Project");
                this.Onid_ProjectChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Guid _id_Project;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onid_ProjectChanging(global::System.Guid value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onid_ProjectChanged();
        /// <summary>
        /// There are no comments for property name_Project in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string name_Project
        {
            get
            {
                return this._name_Project;
            }
            set
            {
                this.Onname_ProjectChanging(value);
                this.ReportPropertyChanging("name_Project");
                this._name_Project = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("name_Project");
                this.Onname_ProjectChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _name_Project;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onname_ProjectChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onname_ProjectChanged();
        /// <summary>
        /// There are no comments for property description_Project in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string description_Project
        {
            get
            {
                return this._description_Project;
            }
            set
            {
                this.Ondescription_ProjectChanging(value);
                this.ReportPropertyChanging("description_Project");
                this._description_Project = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("description_Project");
                this.Ondescription_ProjectChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _description_Project;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Ondescription_ProjectChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Ondescription_ProjectChanged();
        /// <summary>
        /// There are no comments for property comment_Project in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string comment_Project
        {
            get
            {
                return this._comment_Project;
            }
            set
            {
                this.Oncomment_ProjectChanging(value);
                this.ReportPropertyChanging("comment_Project");
                this._comment_Project = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("comment_Project");
                this.Oncomment_ProjectChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _comment_Project;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Oncomment_ProjectChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Oncomment_ProjectChanged();
        /// <summary>
        /// There are no comments for property file_Project in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string file_Project
        {
            get
            {
                return this._file_Project;
            }
            set
            {
                this.Onfile_ProjectChanging(value);
                this.ReportPropertyChanging("file_Project");
                this._file_Project = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("file_Project");
                this.Onfile_ProjectChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _file_Project;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onfile_ProjectChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onfile_ProjectChanged();
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("HERBProject_DataBaseModel", "UsersProjects", "User")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<User> User
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<User>("HERBProject_DataBaseModel.UsersProjects", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<User>("HERBProject_DataBaseModel.UsersProjects", "User", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for HERBProject_DataBaseModel.User in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id_User
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="HERBProject_DataBaseModel", Name="User")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class User : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="id_User">Initial value of id_User.</param>
        /// <param name="name_user">Initial value of name_user.</param>
        /// <param name="lastName_user">Initial value of lastName_user.</param>
        /// <param name="nickname_user">Initial value of nickname_user.</param>
        /// <param name="password_user">Initial value of password_user.</param>
        /// <param name="email_user">Initial value of email_user.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static User CreateUser(global::System.Guid id_User, string name_user, string lastName_user, string nickname_user, string password_user, string email_user)
        {
            User user = new User();
            user.id_User = id_User;
            user.name_user = name_user;
            user.lastName_user = lastName_user;
            user.nickname_user = nickname_user;
            user.password_user = password_user;
            user.email_user = email_user;
            return user;
        }
        /// <summary>
        /// There are no comments for property id_User in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Guid id_User
        {
            get
            {
                return this._id_User;
            }
            set
            {
                this.Onid_UserChanging(value);
                this.ReportPropertyChanging("id_User");
                this._id_User = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("id_User");
                this.Onid_UserChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Guid _id_User;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onid_UserChanging(global::System.Guid value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onid_UserChanged();
        /// <summary>
        /// There are no comments for property name_user in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string name_user
        {
            get
            {
                return this._name_user;
            }
            set
            {
                this.Onname_userChanging(value);
                this.ReportPropertyChanging("name_user");
                this._name_user = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("name_user");
                this.Onname_userChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _name_user;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onname_userChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onname_userChanged();
        /// <summary>
        /// There are no comments for property lastName_user in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string lastName_user
        {
            get
            {
                return this._lastName_user;
            }
            set
            {
                this.OnlastName_userChanging(value);
                this.ReportPropertyChanging("lastName_user");
                this._lastName_user = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("lastName_user");
                this.OnlastName_userChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _lastName_user;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnlastName_userChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnlastName_userChanged();
        /// <summary>
        /// There are no comments for property nickname_user in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string nickname_user
        {
            get
            {
                return this._nickname_user;
            }
            set
            {
                this.Onnickname_userChanging(value);
                this.ReportPropertyChanging("nickname_user");
                this._nickname_user = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("nickname_user");
                this.Onnickname_userChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _nickname_user;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onnickname_userChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onnickname_userChanged();
        /// <summary>
        /// There are no comments for property password_user in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string password_user
        {
            get
            {
                return this._password_user;
            }
            set
            {
                this.Onpassword_userChanging(value);
                this.ReportPropertyChanging("password_user");
                this._password_user = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("password_user");
                this.Onpassword_userChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _password_user;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onpassword_userChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onpassword_userChanged();
        /// <summary>
        /// There are no comments for property email_user in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string email_user
        {
            get
            {
                return this._email_user;
            }
            set
            {
                this.Onemail_userChanging(value);
                this.ReportPropertyChanging("email_user");
                this._email_user = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("email_user");
                this.Onemail_userChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _email_user;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onemail_userChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onemail_userChanged();
        /// <summary>
        /// There are no comments for Project in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("HERBProject_DataBaseModel", "UsersProjects", "Project")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Project> Project
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Project>("HERBProject_DataBaseModel.UsersProjects", "Project");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Project>("HERBProject_DataBaseModel.UsersProjects", "Project", value);
                }
            }
        }
    }
}
